# fly.toml app configuration file generated for winter-dust-9389 on 2023-10-13T00:38:57-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "winter-dust-9389"
primary_region = "bos"

[build]
  image = "flyio/hellofly:latest"

[env]
  PORT = 3000

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
